### ISSUE TITLE
Latest build issues - no Json export, no reboot after flash

### ISSUE THREAD

**Issue by mrslezak** [SmartPack/SmartPack-Kernel-Manager#37]
Not a huge deal but the export profile to Json no longer works.  The reboot after flash doesn't reboot.  At least that's better than the GPlay version where flasher doesn't work at all.  The older versions did export Json though.

**Comment by sunilpaulmathew** [comment]
Hi, thanks for reporting...
By the way, in which section you got the json related issue? If you give me mor details, I'll try to fix it.
Regarding the Reboot after flash issue, I assume that you flashed a custom kernel? In some devices (as I understand), due to the way AK3 zips and Magisk work (not a problem of them in any way, but necessary for its working), the app will lose root temporarily, so that it is no more capable to do root tasks including "Rebooting", unless you restart the app. I'll try to workaround it. By the way, Rebooting after flashing Magisk modules will work fine...
Have a nice day

**Comment by mrslezak** [comment]
It's just the latest build that can't export a Profile to the SP/profiles
directory.  The prior version could.  I made sure it had write permission.
I'm trying to recall the last build that would reboot after a flash - for a
few versions the flash stopped working.  I would say probably before the
Google Pay store release all worked.

**Comment by sunilpaulmathew** [comment]
Hey,
I want to know on what error you got exactly, when you try to import a json file in profile section. Then only I can do something, because it is working fine here (please see this video from my [Dropbox](https://www.dropbox.com/s/6xoio7ddx7uk8tn/20-02-09-17-45-13.mp4?dl=0). Regarding the flash after reboot, yes, it started happening once Magisk has been updated for SAR devices.

**Comment by mrslezak** [comment]
There is no error when trying to SAVE a Profile, no file gets written to
disk.  I check app permissions and read/write is allowed for SmartPack.  It
says it is successful writing out the profile but it's not.  I show that
2/72020 I was able to export a profile to disk, so the version released
just before that date would be the last working one to check for
differences.

**Comment by sunilpaulmathew** [comment]
Really strange, because, as  I remember correctly, I haven't touched anything that possibly make such an error or a long time. Anyway, I'll look on it. Thanks again for the report.
PS: If you can, please show me a screen-record?

**Comment by rama982** [comment]
Same here, can't import json to smartpack, FKM is working fine.

**Comment by sunilpaulmathew** [comment]
json export should be fixed (hopefully) on v9.14.

**Comment by rama982** [comment]
@sunilpaulmathew still not work, json file and link ia from github, no issue with fkm

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew still not work, json file and link is from github, no issue with fkm

Are you talking about linking an update channel json file?

**Comment by rama982** [comment]
> > @sunilpaulmathew still not work, json file and link is from github, no issue with fkm
> 
> Are you talking about linking an update channel json file?

the json is from github raw

**Comment by sunilpaulmathew** [comment]
> > > @sunilpaulmathew still not work, json file and link is from github, no issue with fkm
> > 
> > 
> > Are you talking about linking an update channel json file?
> 
> the json is from github raw

Can I have the link (of json) please, to test here?

**Comment by rama982** [comment]
@sunilpaulmathew this is json link example
https://github.com/Genom-Project/FKM/raw/master/ginkgo.json

When inputing i get invalid url toast error.

**Comment by sunilpaulmathew** [comment]
I just tested it here and worked well (ofc, I haven't tested flashing). Also, please check this [Dropbox video](https://www.dropbox.com/s/1ef6bcurabmgybe/20-02-29-11-34-01.mp4?dl=0).
So, my conclusions are:
This app uses curl/wget (either one) binaries to acquire update info (and also to download kernel) from the update channel. I assume that your device doesn't have any of those required binaries at this moment (you must be on an early Android 10 build, and I hope one of them could be soon introduced for your device). You can check it by running "**curl --help**" or "**wget --help**" on a terminal screen.  I have no idea about how other closed source paid apps works, so please do not compare. I shall add a binary check in the future version to let the user know the issue in advance.

Thanks

**Comment by HessNL** [comment]
if you added spaces to save Json then it doesn't work
