### ISSUE TITLE
Unable to reach last item in scrolling menus

### ISSUE THREAD

**Issue by mario0318** [SmartPack/SmartPack-Kernel-Manager#76]
There appears to be an issue with the latest app update where on any scroll menu within the app, if there are enough entries in the menu to require scrolling, the very last item at the bottom remains just shy of fully appearing, almost as if the scroll variable is set to n-1, where n is the number of items to display in the menu.

![Screenshot_20200827-012028_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/25380627/91389010-7a729980-e806-11ea-8d82-97fd988a82c5.png)

However, because the item boxes are padded, it does show the very top of the box, but it will not scroll down any further. The two pictures here hopefully show what I'm referring to. On the CPU governor tunables, for interactive, the very last item is "use sched load". Notice the padding for the item box is there and I can tap it and it opens the edit window just fine. Same with the photo for CFQ scheduler, the last item is "target latency" but unable to scroll all the way down to see it. Below are two screenshots one as it is and the second one where I'm holding the item box to show it can be tapped on. 
![Screenshot_20200827-012106_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/25380627/91389033-83fc0180-e806-11ea-9f50-3ccfc3bc6b19.png)
![Screenshot_20200827-014632_SmartPack-Kernel_Manager](https://user-images.githubusercontent.com/25380627/91389824-36cc5f80-e807-11ea-9ef8-2a29886d5848.png)

It worked as it should on past versions. Issue appears to have begun with the latest 13.0. I'm on SPKM Pro.

**Comment by sunilpaulmathew** [comment]
@mario0318 
Thanks for reporting. It is a small margin issue and I thought it is already fixed in an earlier version. I will try to reproduce and fix it soon.

**Comment by mario0318** [comment]
Have you had any luck with reproducing the problem and finding a fix? Both of the latest updates so far still appear to contain this lil bugger.

**Comment by sunilpaulmathew** [comment]
> the latest updates so far st

I'm extremely sorry for not updating you. I can't reproduce the issue here. I just forwarded this report into our telegram support group to find more people affected (if any). I hope it will work.

**Comment by sunilpaulmathew** [comment]
Although after a long delay, this issue is finally fixed forever. So, closing this issue.
